"""Deployment-only NanoQuant runtime surface.

This package must remain importable without calibration, datasets, factorization,
optimizers, or experiment orchestration.
"""

from nanoquant.runtime.artifact import (
    DESCRIPTOR_SCHEMA_VERSION,
    LOGICAL_FORMAT_VERSION,
    LogicalArtifactError,
    LogicalModelManifest,
    OpenLogicalArtifact,
    RuntimeModelMetadata,
    open_logical_artifact,
    write_logical_artifact,
    write_logical_artifact_stream,
)
from nanoquant.runtime.backend import (
    BackendCapabilities,
    PreparedLayer,
    QuantizedLinearSpec,
    RuntimeBackend,
    SupportResult,
    WorkloadSpec,
)
from nanoquant.runtime.cuda_backend import (
    CUDA_PACKED_BACKEND_VERSION,
    CUDA_PACKED_REFERENCE_SHA256,
    CudaPackedBackend,
)
from nanoquant.runtime.llamacpp import (
    LLAMACPP_CHECKPOINT_FORMAT,
    LLAMACPP_CHECKPOINT_SCHEMA_VERSION,
    LlamaCppCheckpointManifest,
    export_llamacpp_checkpoint,
    gemma_gguf_tensor_prefix,
    gemma_hf_checkpoint_prefix,
    llamacpp_checkpoint_tensors,
)
from nanoquant.runtime.logical import LogicalLayerState, canonical_torch_dtype
from nanoquant.runtime.packed import (
    GGUF_TENSOR_SUFFIXES,
    PACKED_LAYOUT_VERSION,
    PACKED_REFERENCE_COMMIT,
    PACKED_REFERENCE_CONVERTER_SHA256,
    PACKED_REFERENCE_CPU_SHA256,
    PACKED_REFERENCE_CUDA_SHA256,
    PACKED_REFERENCE_DIRTY_DIFF_GIT_OBJECT,
    PACKED_REFERENCE_DOCUMENTATION_SHA256,
    PACKED_REFERENCE_MODEL_LOADER_SHA256,
    PACKED_REFERENCE_REPOSITORY,
    PACKED_TENSOR_NAMESPACE,
    PACKED_WORD_BITS,
    PACKED_WORD_DTYPE,
    PackedLayerState,
    PackedLayoutMetadata,
    PackedReferenceProvenance,
    pack_logical_layer,
    pack_sign_matrix,
    packed_row_stride_bytes,
    packed_word_count,
    supports_vector_word_loads,
    unpack_sign_matrix,
)
from nanoquant.runtime.packed_artifact import (
    PACKED_ARTIFACT_FORMAT,
    PACKED_DESCRIPTOR_SCHEMA_VERSION,
    OpenPackedArtifact,
    PackedArtifactError,
    PackedConversionValidation,
    PackedModelManifest,
    PackedReferenceParityResult,
    convert_logical_to_packed,
    open_packed_artifact,
    validate_packed_conversion,
    validate_packed_reference_parity,
    write_packed_artifact,
    write_packed_artifact_stream,
)
from nanoquant.runtime.planning import (
    BackendPlan,
    BackendPlanningError,
    LayerDispatch,
    PreparedDispatch,
    plan_backends,
    prepare_plan,
)
from nanoquant.runtime.reference import (
    DenseReferenceBackend,
    FactorizedReferenceBackend,
    PackedReferenceBackend,
)
from nanoquant.runtime.validation import (
    ReferenceParityError,
    ReferenceParityResult,
    validate_logical_reference_parity,
)

__all__ = [
    "BackendCapabilities",
    "BackendPlan",
    "BackendPlanningError",
    "CUDA_PACKED_BACKEND_VERSION",
    "CUDA_PACKED_REFERENCE_SHA256",
    "CudaPackedBackend",
    "DenseReferenceBackend",
    "FactorizedReferenceBackend",
    "LayerDispatch",
    "LOGICAL_FORMAT_VERSION",
    "DESCRIPTOR_SCHEMA_VERSION",
    "LogicalArtifactError",
    "LogicalLayerState",
    "LogicalModelManifest",
    "LLAMACPP_CHECKPOINT_FORMAT",
    "LLAMACPP_CHECKPOINT_SCHEMA_VERSION",
    "LlamaCppCheckpointManifest",
    "OpenLogicalArtifact",
    "OpenPackedArtifact",
    "GGUF_TENSOR_SUFFIXES",
    "PACKED_LAYOUT_VERSION",
    "PACKED_REFERENCE_COMMIT",
    "PACKED_REFERENCE_CONVERTER_SHA256",
    "PACKED_REFERENCE_CPU_SHA256",
    "PACKED_REFERENCE_CUDA_SHA256",
    "PACKED_REFERENCE_DIRTY_DIFF_GIT_OBJECT",
    "PACKED_REFERENCE_DOCUMENTATION_SHA256",
    "PACKED_REFERENCE_MODEL_LOADER_SHA256",
    "PACKED_REFERENCE_REPOSITORY",
    "PACKED_TENSOR_NAMESPACE",
    "PACKED_ARTIFACT_FORMAT",
    "PACKED_DESCRIPTOR_SCHEMA_VERSION",
    "PACKED_WORD_BITS",
    "PACKED_WORD_DTYPE",
    "PackedLayerState",
    "PackedLayoutMetadata",
    "PackedArtifactError",
    "PackedConversionValidation",
    "PackedModelManifest",
    "PackedReferenceBackend",
    "PackedReferenceProvenance",
    "PackedReferenceParityResult",
    "PreparedDispatch",
    "PreparedLayer",
    "QuantizedLinearSpec",
    "ReferenceParityError",
    "ReferenceParityResult",
    "RuntimeBackend",
    "RuntimeModelMetadata",
    "SupportResult",
    "WorkloadSpec",
    "canonical_torch_dtype",
    "convert_logical_to_packed",
    "export_llamacpp_checkpoint",
    "gemma_gguf_tensor_prefix",
    "gemma_hf_checkpoint_prefix",
    "plan_backends",
    "pack_logical_layer",
    "pack_sign_matrix",
    "packed_row_stride_bytes",
    "packed_word_count",
    "open_logical_artifact",
    "open_packed_artifact",
    "llamacpp_checkpoint_tensors",
    "prepare_plan",
    "write_logical_artifact",
    "write_logical_artifact_stream",
    "write_packed_artifact",
    "write_packed_artifact_stream",
    "validate_logical_reference_parity",
    "validate_packed_conversion",
    "validate_packed_reference_parity",
    "supports_vector_word_loads",
    "unpack_sign_matrix",
]
