"""Canonical promoted experiment recipes."""

from .base_compression import BASE_COMPRESSION_CONFIG, compression_export_recipe
from .experiment001 import EXPERIMENT_001, EXPERIMENT_001_CONFIG
from .experiment002 import EXPERIMENT_002_CONFIG, EXPERIMENT_002_EVALUATION
from .experiment003 import EXPERIMENT_003, EXPERIMENT_003_CONFIG
from .experiment004 import EXPERIMENT_004, EXPERIMENT_004_CONFIG
from .experiment008 import EXPERIMENT_008_CONFIG
from .experiment011 import EXPERIMENT_011_BENCHMARK, EXPERIMENT_011_CONFIG
from .experiment013 import EXPERIMENT_013_CONFIG
from .experiment018 import EXPERIMENT_018_CONFIG

__all__ = [
    "BASE_COMPRESSION_CONFIG",
    "compression_export_recipe",
    "EXPERIMENT_001_CONFIG",
    "EXPERIMENT_001",
    "EXPERIMENT_002_CONFIG",
    "EXPERIMENT_002_EVALUATION",
    "EXPERIMENT_003_CONFIG",
    "EXPERIMENT_003",
    "EXPERIMENT_004_CONFIG",
    "EXPERIMENT_004",
    "EXPERIMENT_008_CONFIG",
    "EXPERIMENT_011_BENCHMARK",
    "EXPERIMENT_011_CONFIG",
    "EXPERIMENT_013_CONFIG",
    "EXPERIMENT_018_CONFIG",
]
