from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Protocol

import torch


class ActivationStore(Protocol):
    kind: str

    def put(self, key: str, value: torch.Tensor) -> None: ...
    def read(self, key: str, device: str | None = None) -> AbstractContextManager[torch.Tensor]: ...
    def remove(self, key: str) -> None: ...
    def clear(self) -> None: ...


class BatchGenerationWriter(Protocol):
    def write(self, selection: slice, values: torch.Tensor) -> None: ...
    def commit(self) -> str: ...

    def __enter__(self) -> BatchGenerationWriter: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...


class GenerationActivationStore(ActivationStore, Protocol):
    def begin_generation(
        self, key: str, shape: tuple[int, ...], dtype: torch.dtype = torch.float32
    ) -> BatchGenerationWriter: ...
