from __future__ import annotations

from typing import Protocol

from torch import Tensor, nn

from nanoquant.domain.models import BlockId, BlockInventory, LayerId, ModelInventory

from .model_source import ModelSource


class ModelAdapter(Protocol):
    family: str
    version: str

    def decoder_block_count(self, source: ModelSource) -> int: ...
    def model_inventory(self, source: ModelSource) -> ModelInventory: ...
    def block_inventory(self, source: ModelSource, block_id: BlockId) -> BlockInventory: ...
    def source_key(self, layer: LayerId, tensor_name: str = "weight") -> str: ...
    def quantizable_layers(self, block: nn.Module, block_id: BlockId) -> tuple[LayerId, ...]: ...
    def construct_block(self, source: ModelSource, block_id: BlockId, device: str) -> nn.Module: ...
    def load_block(self, source: ModelSource, block_id: BlockId, device: str) -> nn.Module: ...
    def run_prefix(self, model: nn.Module, tokens: Tensor) -> Tensor: ...
    def run_block(self, block: nn.Module, inputs: Tensor, **kwargs: object) -> Tensor: ...
    def run_suffix(self, model: nn.Module, inputs: Tensor) -> Tensor: ...
    def lm_head(self, model: nn.Module) -> nn.Module: ...
